(()=>{
 const ACTIVITIES={cycling:{label:'Cycling',icon:'🚲',verb:'Ride',speed:12},ebike:{label:'E-bike',icon:'⚡',verb:'Ride',speed:15},walking:{label:'Walking',icon:'🚶',verb:'Walk',speed:3},jogging:{label:'Jogging',icon:'🏃',verb:'Jog',speed:5},running:{label:'Running',icon:'🏃',verb:'Run',speed:6.5},hiking:{label:'Hiking',icon:'🥾',verb:'Hike',speed:2.5}};
 function current(){return localStorage.getItem('trailride-activity')||'cycling'}
 function set(v){if(!ACTIVITIES[v])v='cycling';localStorage.setItem('trailride-activity',v);apply(v)}
 function apply(v=current()){let a=ACTIVITIES[v]||ACTIVITIES.cycling,sel=document.getElementById('activitySelect');if(sel&&sel.value!==v)sel.value=v;document.querySelector('.hero .eyebrow')?.replaceChildren(document.createTextNode(`${a.label.toUpperCase()} CONDITIONS`));let p=document.querySelector('.hero p');if(p)p.textContent=`Nearby trails • weather • ${v==='cycling'||v==='ebike'?'Ride':'Activity'} Score`;document.querySelectorAll('.rideScoreRow small').forEach(x=>x.textContent=`/10 ${v==='cycling'||v==='ebike'?'Ride':'Activity'} Score`);let wh=document.querySelector('.weekPlanner h2');if(wh)wh.textContent=`Best day to ${a.verb.toLowerCase()}`;let hh=document.querySelector('.hourlyCard')?.previousElementSibling?.querySelector('h2');if(hh)hh.textContent=`Best time to ${a.verb.toLowerCase()}`;document.body.dataset.activity=v;filterCards(v);decorateTimes(v)}
 function allowed(card,v){let meta=(card.querySelector('.meta')?.textContent||'').toLowerCase(),name=(card.querySelector('.trailName')?.textContent||'').toLowerCase();if(v==='cycling'||v==='ebike')return !/hiking only|footpath only|no bikes/.test(meta);if(v==='walking'||v==='jogging'||v==='running')return !/bike only|mtb only/.test(meta);if(v==='hiking')return true;return true}
 function filterCards(v){document.querySelectorAll('#trailList .trail').forEach(c=>{c.style.display=allowed(c,v)?'':'none'})}
 function decorateTimes(v){let a=ACTIVITIES[v]||ACTIVITIES.cycling;document.querySelectorAll('#trailList .trail').forEach(c=>{let meta=c.querySelector('.meta')?.textContent||'',m=meta.match(/([\d.]+)\s*mi/i),old=c.querySelector('.activityEstimate');if(!m){old?.remove();return}let hrs=(+m[1])/a.speed,min=Math.round(hrs*60),txt=min<60?`${min} min`:min%60?`${Math.floor(min/60)} hr ${min%60} min`:`${min/60} hr`;if(!old){old=document.createElement('div');old.className='activityEstimate';old.style.cssText='margin-top:7px;font-size:12px;opacity:.8';c.querySelector('.meta')?.insertAdjacentElement('afterend',old)}old.textContent=`${a.icon} Estimated ${a.verb.toLowerCase()} time: ${txt}`})}
 function boot(){let filters=document.querySelector('.searchGrid');if(filters&&!document.getElementById('activitySelect')){let label=document.createElement('label');label.innerHTML='Activity<select id="activitySelect"><option value="cycling">🚲 Cycling</option><option value="ebike">⚡ E-bike</option><option value="walking">🚶 Walking</option><option value="jogging">🏃 Jogging</option><option value="running">🏃 Running</option><option value="hiking">🥾 Hiking</option></select>';filters.prepend(label);label.querySelector('select').addEventListener('change',e=>set(e.target.value))}let list=document.getElementById('trailList');if(list)new MutationObserver(()=>apply()).observe(list,{childList:true});apply()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();window.TrailRideActivity={current,set,apply,activities:ACTIVITIES};
})();