(()=>{
 const ACTIVITIES={cycling:{label:'Cycling',icon:'🚲',verb:'Ride',speed:12},ebike:{label:'E-bike',icon:'⚡',verb:'Ride',speed:15},walking:{label:'Walking',icon:'🚶',verb:'Walk',speed:3},jogging:{label:'Jogging',icon:'🏃',verb:'Jog',speed:5},running:{label:'Running',icon:'🏃',verb:'Run',speed:6.5},hiking:{label:'Hiking',icon:'🥾',verb:'Hike',speed:2.5}};
 function current(){return localStorage.getItem('trailride-activity')||'cycling'}
 function set(v){if(!ACTIVITIES[v])v='cycling';localStorage.setItem('trailride-activity',v);apply(v);window.dispatchEvent(new CustomEvent('trailride:activitychange',{detail:{activity:v}}))}
 function apply(v=current()){let a=ACTIVITIES[v]||ACTIVITIES.cycling,sel=document.getElementById('activitySelect');if(sel&&sel.value!==v)sel.value=v;document.querySelector('.hero .eyebrow')?.replaceChildren(document.createTextNode(`${a.label.toUpperCase()} CONDITIONS`));let p=document.querySelector('.hero p');if(p)p.textContent=`Nearby trails • weather • ${v==='cycling'||v==='ebike'?'Ride':'Activity'} Score`;document.querySelectorAll('.rideScoreRow small').forEach(x=>x.textContent=`/10 ${v==='cycling'||v==='ebike'?'Ride':'Activity'} Score`);let wh=document.querySelector('.weekPlanner h2');if(wh)wh.textContent=`Best day to ${a.verb.toLowerCase()}`;let hh=document.querySelector('.hourlyCard')?.previousElementSibling?.querySelector('h2');if(hh)hh.textContent=`Best time to ${a.verb.toLowerCase()}`;document.body.dataset.activity=v;filterCards(v);decorateTimes(v)}
 function allowed(card,v){let meta=(card.querySelector('.meta')?.textContent||'').toLowerCase();if(v==='cycling'||v==='ebike')return !/hiking only|footpath only|no bikes|pedestrian only/.test(meta);if(v==='walking'||v==='jogging'||v==='running')return !/bike only|mtb only/.test(meta);if(v==='hiking')return !/bike only/.test(meta);return true}
 function filterCards(v){document.querySelectorAll('#trailList .trail').forEach(c=>{c.style.display=allowed(c,v)?'':'none'})}
 function decorateTimes(v){let a=ACTIVITIES[v]||ACTIVITIES.cycling;document.querySelectorAll('#trailList .trail').forEach(c=>{let meta=c.querySelector('.meta')?.textContent||'',m=meta.match(/([\d.]+)\s*mi/i),old=c.querySelector('.activityEstimate');if(!m){old?.remove();return}let hrs=(+m[1])/a.speed,min=Math.round(hrs*60),txt=min<60?`${min} min`:min%60?`${Math.floor(min/60)} hr ${min%60} min`:`${min/60} hr`;if(!old){old=document.createElement('div');old.className='activityEstimate';old.style.cssText='margin-top:7px;font-size:12px;opacity:.8';c.querySelector('.meta')?.insertAdjacentElement('afterend',old)}old.textContent=`${a.icon} Estimated ${a.verb.toLowerCase()} time: ${txt}`})}
 function boot(){let filters=document.querySelector('.searchGrid');if(filters&&!document.getElementById('activitySelect')){let label=document.createElement('label');label.innerHTML='Activity<select id="activitySelect"><option value="cycling">🚲 Cycling</option><option value="ebike">⚡ E-bike</option><option value="walking">🚶 Walking</option><option value="jogging">🏃 Jogging</option><option value="running">🏃 Running</option><option value="hiking">🥾 Hiking</option></select>';filters.prepend(label);label.querySelector('select').addEventListener('change',e=>set(e.target.value))}let list=document.getElementById('trailList');if(list)new MutationObserver(()=>apply()).observe(list,{childList:true});apply()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();window.TrailRideActivity={current,set,apply,activities:ACTIVITIES};
})();

(()=>{
 const KEY='trailride-gps-sessions',rad=x=>x*Math.PI/180;
 const meters=(a,b,c,d)=>{const R=6371000,x=Math.sin(rad(c-a)/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(rad(d-b)/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
 const mode=()=>String(window.TrailRideActivity?.current?.()||'cycling').toLowerCase();
 const cap=a=>a.includes('walk')||a.includes('hik')?12:a.includes('jog')?18:a.includes('run')?25:a.includes('ebike')||a.includes('e-bike')?45:55;
 function installGpsFilter(){const geo=navigator.geolocation;if(!geo||geo.__trailRideFiltered)return;const original=geo.watchPosition.bind(geo);geo.watchPosition=(success,error,opts)=>{let last=null;return original(pos=>{const c=pos?.coords;if(!c)return;const lat=Number(c.latitude),lon=Number(c.longitude),acc=Number(c.accuracy),ts=Number(pos.timestamp)||Date.now(),limit=cap(mode())*1.2;if(!Number.isFinite(lat)||!Number.isFinite(lon)||(Number.isFinite(acc)&&acc>80))return;let rawSpeed=Number(c.speed),mph=Number.isFinite(rawSpeed)&&rawSpeed>=0?rawSpeed*2.236936:null;if(last){const dt=(ts-last.ts)/1000;if(dt>.4&&dt<120){const d=meters(last.lat,last.lon,lat,lon),implied=d/dt*2.236936,unc=Math.max(Number.isFinite(acc)?acc:25,last.acc);if(implied>limit&&d>Math.max(25,unc*1.5))return}}if(mph!==null&&mph>limit)rawSpeed=null;last={lat,lon,acc:Number.isFinite(acc)?acc:25,ts};success({coords:{latitude:lat,longitude:lon,accuracy:Number.isFinite(acc)?acc:0,altitude:Number.isFinite(Number(c.altitude))?Number(c.altitude):null,altitudeAccuracy:Number.isFinite(Number(c.altitudeAccuracy))?Number(c.altitudeAccuracy):null,heading:Number.isFinite(Number(c.heading))?Number(c.heading):null,speed:rawSpeed},timestamp:ts})},error,opts)};geo.__trailRideFiltered=true}
 function cleanOldSpeeds(){let sessions;try{sessions=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return}if(!Array.isArray(sessions))return;let changed=false;for(const s of sessions){const a=String(s.activity||'cycling').toLowerCase(),limit=cap(a);if(Number(s.maxSpeed)>limit){let best=0,last=null;for(const p of Array.isArray(s.points)?s.points:[]){const lat=Number(p.lat),lon=Number(p.lon),t=Number(p.t),acc=Number(p.acc),direct=Number(p.speed);if(Number.isFinite(direct)&&direct>=0&&direct*2.236936<=limit)best=Math.max(best,direct*2.236936);if(last&&Number.isFinite(lat)&&Number.isFinite(lon)&&Number.isFinite(t)){const dt=(t-last.t)/1000;if(dt>.4&&dt<120){const d=meters(last.lat,last.lon,lat,lon),mph=d/dt*2.236936,unc=Math.max(Number.isFinite(acc)?acc:25,last.acc);if(mph<=limit&&d<=Math.max(250,unc*6))best=Math.max(best,mph)}}if(Number.isFinite(lat)&&Number.isFinite(lon)&&Number.isFinite(t))last={lat,lon,t,acc:Number.isFinite(acc)?acc:25}}s.maxSpeed=+best.toFixed(2);changed=true}if(Number(s.avgSpeed)>limit){const hrs=Math.max(0,Number(s.duration)||0)/36e5;s.avgSpeed=hrs>0?+(Math.max(0,Number(s.distance)||0)/hrs).toFixed(2):0;changed=true}}if(changed){localStorage.setItem(KEY,JSON.stringify(sessions));setTimeout(()=>window.dispatchEvent(new Event('trailride:gps-saved')),50)}}
 installGpsFilter();cleanOldSpeeds();
})();