(()=>{
 const KEY='trailride-gps-sessions';
 function sessions(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 function fileName(s){const base=(s.trailName||s.trail?.name||s.activity||'TrailRide').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-+|-+$/g,'')||'TrailRide';const d=new Date(Number(s.started)||Number(s.id)||Date.now()).toISOString().slice(0,10);return `${base}-${d}.gpx`}
 function buildGPX(s){const pts=(s.points||[]).filter(p=>Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lon)));if(!pts.length)return null;const name=s.trailName||s.trail?.name||'TrailRide recorded ride';const trk=pts.map(p=>{const ele=Number.isFinite(Number(p.alt))?`<ele>${Number(p.alt).toFixed(2)}</ele>`:'';const tm=new Date(Number(p.t)||Number(s.started)||Date.now()).toISOString();return `<trkpt lat="${Number(p.lat).toFixed(7)}" lon="${Number(p.lon).toFixed(7)}">${ele}<time>${tm}</time></trkpt>`}).join('');return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="TrailRide Near Me" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">\n<metadata><name>${esc(name)}</name><time>${new Date(Number(s.started)||Date.now()).toISOString()}</time></metadata>\n<trk><name>${esc(name)}</name><type>${esc(s.activity||'cycling')}</type><trkseg>${trk}</trkseg></trk>\n</gpx>`}
 async function exportSession(s,btn){const gpx=buildGPX(s);if(!gpx){btn.textContent='No GPS Data';btn.disabled=true;return}const name=fileName(s),blob=new Blob([gpx],{type:'application/gpx+xml'}),file=new File([blob],name,{type:'application/gpx+xml'});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'TrailRide GPX',text:s.trailName||s.trail?.name||'Recorded ride',files:[file]});return}}catch(e){if(e?.name==='AbortError')return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
 function decorate(){const ss=sessions(),rows=[...document.querySelectorAll('#rideDashboard .recordedRideItem')];rows.forEach((row,i)=>{if(row.dataset.gpxReady==='1')return;const s=ss[i];if(!s)return;const acts=row.querySelector('.rideItemActions');if(!acts)return;const b=document.createElement('button');b.className='miniBtn gpxBtn';b.textContent='Export GPX';b.onclick=()=>exportSession(s,b);acts.insertBefore(b,acts.querySelector('.remove')||null);row.dataset.gpxReady='1'})}
 function boot(){decorate();const dash=document.getElementById('rideDashboard');if(dash)new MutationObserver(()=>setTimeout(decorate,0)).observe(dash,{childList:true,subtree:true});window.addEventListener('trailride:gps-saved',()=>setTimeout(decorate,0));window.addEventListener('storage',()=>setTimeout(decorate,0))}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();