(()=>{
 const key=s=>String(s||'').trim().toLowerCase();
 let savedY=0;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const findTrail=name=>{try{return (typeof trails!=='undefined'?trails:[]).find(t=>key(t.name)===key(name))||null}catch{return null}};
 function selectedDate(){return document.getElementById('daySelect')?.value||new Date().toISOString().slice(0,10)}
 function fmtHour(t){let h=+String(t).slice(11,13);return `${h%12||12} ${h<12?'AM':'PM'}`}
 function endHour(t){let h=(+String(t).slice(11,13)+1)%24;return `${h%12||12} ${h<12?'AM':'PM'}`}
 async function weatherAt(lat,lon){const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation&daily=temperature_2m_max,precipitation_probability_max,precipitation_sum&temperature_unit=fahrenheit&precipitation_unit=inch&timezone=auto&past_days=2&forecast_days=8`);return r.json()}
 async function airAt(lat,lon){const r=await fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&hourly=us_aqi,pm2_5,ozone&timezone=auto&forecast_days=7`);return r.json()}
 function rows(ws,as,t){if(!ws?.hourly?.time)return[];const date=selectedDate(),out=[];ws.hourly.time.forEach((time,i)=>{if(time.slice(0,10)!==date)return;const hr=+time.slice(11,13);if(hr<6||hr>20)return;const ai=as?.hourly?.time?.indexOf(time)??-1,aq={aqi:ai>=0?(+as.hourly.us_aqi?.[ai]||0):null,pm:ai>=0?(+as.hourly.pm2_5?.[ai]||0):null,ozone:ai>=0?(+as.hourly.ozone?.[ai]||0):null},temp=+ws.hourly.temperature_2m[i]||0,rain=+ws.hourly.precipitation_probability[i]||0,hum=+ws.hourly.relative_humidity_2m[i]||0;let score=Math.max(1,10-(temp>=95?3:temp>=90?2:temp>=85?1:0)-(rain>=70?3:rain>=40?1.5:rain>=20?.5:0)-(hum>=85?1:hum>=75?.4:0)-(aq.aqi>150?2.5:aq.aqi>100?1.5:aq.aqi>50?.5:0));try{if(typeof scoreHour==='function')score=scoreHour(temp,rain,hum,aq,t)}catch{}out.push({time,temp,rain,hum,aqi:aq.aqi,score:+score.toFixed(1)})});return out}
 function bestWindow(a){let best=null;for(let i=0;i<=a.length-3;i++){const g=a.slice(i,i+3),avg=g.reduce((s,x)=>s+x.score,0)/3;if(!best||avg>best.avg)best={start:g[0],end:g[2],avg}}return best}
 function ensure(){if(document.getElementById('trailFocusOverlay'))return;const o=document.createElement('div');o.id='trailFocusOverlay';o.style.cssText='position:fixed;inset:0;z-index:2147483000;background:#071416;display:none;overflow-y:auto;-webkit-overflow-scrolling:touch;padding:env(safe-area-inset-top) 0 env(safe-area-inset-bottom);';o.innerHTML=`<section id="trailFocusSheet" style="width:100%;min-height:100dvh;background:#071416;margin:0;overflow:hidden"><div style="position:sticky;top:0;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;background:#071416;border-bottom:1px solid rgba(255,255,255,.14)"><div><div class="eyebrow">SELECTED TRAIL</div><strong id="trailFocusTitle" style="font-size:20px">Trail details</strong></div><button id="trailFocusClose" class="closeBtn" aria-label="Close" style="min-width:52px;min-height:48px">×</button></div><div id="trailFocusBody" style="padding:12px 12px 90px;max-width:760px;margin:0 auto"></div></section>`;document.body.appendChild(o);document.getElementById('trailFocusClose').onclick=close}
 function hideOldDetail(){const old=document.getElementById('detailOverlay');if(old)old.classList.add('hidden');document.documentElement.classList.remove('trail-detail-open');document.body.classList.remove('trail-detail-open')}
 function close(){const o=document.getElementById('trailFocusOverlay');if(!o)return;o.style.display='none';document.documentElement.style.overflow='';document.body.style.overflow='';window.scrollTo(0,savedY)}
 function copyTrailCard(card){const clone=card.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('.detailsBtn').forEach(x=>x.remove());clone.querySelectorAll('.trailSystemPanel').forEach(x=>x.remove());const start=clone.querySelector('.startTrailRideBtn');if(start)start.onclick=()=>{const name=card.querySelector('.trailName')?.textContent||'Trail',t=findTrail(name)||{name};close();window.dispatchEvent(new CustomEvent('trailride:start-trail-ride',{detail:{name:t.name||name,city:t.city||'',state:t.state||'',lat:t.lat,lon:t.lon}}))};const nav=clone.querySelector('.navigateTrailBtn');if(nav)nav.onclick=()=>{const name=card.querySelector('.trailName')?.textContent||'Trail',t=findTrail(name)||{name};close();window.dispatchEvent(new CustomEvent('trailride:navigate-trail',{detail:t}))};const pin=clone.querySelector('.pinBtn');if(pin)pin.onclick=()=>{card.querySelector('.pinBtn')?.click();close()};const fav=clone.querySelector('.favBtn');if(fav)fav.onclick=()=>{card.querySelector('.favBtn')?.click();fav.textContent=card.querySelector('.favBtn')?.textContent||fav.textContent};return clone}
 async function open(card){ensure();hideOldDetail();savedY=window.scrollY;const o=document.getElementById('trailFocusOverlay'),body=document.getElementById('trailFocusBody'),name=card.querySelector('.trailName')?.textContent||'Trail',t=findTrail(name)||{name};document.getElementById('trailFocusTitle').textContent=name;body.innerHTML='';const clone=copyTrailCard(card);body.appendChild(clone);const hourly=document.createElement('section');hourly.className='card hourlyCard';hourly.style.marginTop='12px';hourly.innerHTML=`<div class="eyebrow">HOURLY TRAIL SCORE</div><h2>${esc(name)}</h2><div class="focusBestWindow bestWindow">Loading hourly score…</div><div class="focusHourlyList hourlyList"></div><p class="focusHourlyNote locationText">Scores use this trail’s weather, air quality, selected day and your rider considerations.</p>`;body.appendChild(hourly);o.style.display='block';document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';o.scrollTop=0;if(!t.lat||!t.lon){hourly.querySelector('.focusBestWindow').textContent='Hourly score unavailable because this trail has no mapped location.';return}try{const [ws,as]=await Promise.all([weatherAt(t.lat,t.lon),airAt(t.lat,t.lon)]),a=rows(ws,as,t),b=bestWindow(a);if(!a.length){hourly.querySelector('.focusBestWindow').textContent='Hourly forecast unavailable for the selected day.';return}hourly.querySelector('.focusBestWindow').innerHTML=b?`⭐ Best 3-hour window: <strong>${fmtHour(b.start.time)}–${endHour(b.end.time)}</strong> • ${b.avg.toFixed(1)}/10`:'Hourly trail scores';hourly.querySelector('.focusHourlyList').innerHTML=a.map(x=>`<div class="hour ${x.score>=8?'great':x.score>=6?'fair':'poor'}"><strong>${fmtHour(x.time)}</strong><span>${Math.round(x.temp)}°</span><small>Rain ${x.rain}%</small><small>Humidity ${x.hum}%</small><small>AQI ${x.aqi==null?'--':Math.round(x.aqi)}</small><b>${x.score}</b></div>`).join('')}catch(e){hourly.querySelector('.focusBestWindow').textContent='Could not load this trail’s hourly forecast right now.'}}
 function intercept(e){const b=e.target.closest?.('.detailsBtn');if(!b)return;const card=b.closest('.trail');if(!card)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open(card)}
 document.addEventListener('click',intercept,true);
 function boot(){ensure()}
 window.TrailRideTrailFocus={open,close};
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();