(()=>{
 const KEY='trailride-trips';
 const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
 const put=x=>localStorage.setItem(KEY,JSON.stringify(x));
 const activity=()=>window.TrailRideActivity?.current?.()||localStorage.getItem('trailride-activity')||'cycling';
 const label=a=>({cycling:'Cycling',ebike:'E-bike',walking:'Walking',jogging:'Jogging',running:'Running',hiking:'Hiking'}[a]||'Cycling');
 function css(){let s=document.createElement('style');s.textContent='.tripPlanner{margin-top:14px}.tripGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tripGrid label{font-size:12px}.tripGrid input,.tripGrid select{width:100%;margin-top:5px}.tripActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.tripSaved{margin-top:12px;display:grid;gap:8px}.tripItem{padding:10px;border:1px solid rgba(255,255,255,.12);border-radius:12px}.tripItem small{display:block;opacity:.75;margin-top:4px}.tripItem button{margin-top:7px}@media(max-width:600px){.tripGrid{grid-template-columns:1fr}}';document.head.appendChild(s)}
 function boot(){
  css();let controls=document.querySelector('.controls.card');if(!controls||document.getElementById('tripPlanner'))return;
  let box=document.createElement('section');box.id='tripPlanner';box.className='tripPlanner';box.innerHTML=`<div class="eyebrow">TRIP PLANNER</div><h2>Plan an activity trip</h2><div class="tripGrid"><label>Destination<input id="tripDestination" placeholder="Panama City Beach"></label><label>Trip date<input id="tripDate" type="date"></label><label>Activity<select id="tripActivity"><option value="cycling">🚲 Cycling</option><option value="ebike">⚡ E-bike</option><option value="walking">🚶 Walking</option><option value="jogging">🏃 Jogging</option><option value="running">🏃 Running</option><option value="hiking">🥾 Hiking</option></select></label><label>Search radius<select id="tripRadius"><option value="15">15 min</option><option value="30">30 min</option><option value="60">1 hour</option><option value="120" selected>2 hours</option><option value="all">Search farther</option></select></label></div><div class="tripActions"><button id="tripFind" class="primary">Find Best Trails</button><button id="tripSave" class="ghost">Save Trip</button></div><div id="tripStatus" class="locationText"></div><div id="tripSaved" class="tripSaved"></div>`;
  controls.appendChild(box);let d=new Date();d.setDate(d.getDate()+1);document.getElementById('tripDate').value=d.toISOString().slice(0,10);document.getElementById('tripActivity').value=activity();
  document.getElementById('tripFind').onclick=find;document.getElementById('tripSave').onclick=save;renderSaved();
 }
 async function find(){let dest=document.getElementById('tripDestination').value.trim(),date=document.getElementById('tripDate').value,a=document.getElementById('tripActivity').value,r=document.getElementById('tripRadius').value,status=document.getElementById('tripStatus');if(!dest){status.textContent='Enter a city or area first.';return}status.textContent=`Finding ${label(a).toLowerCase()} trails around ${dest}…`;window.TrailRideActivity?.set?.(a);let rs=document.getElementById('radius');if(rs)rs.value=r;let day=document.getElementById('daySelect');if(day&&date&&[...day.options].some(o=>o.value===date))day.value=date;let q=document.getElementById('trailSearch');if(q)q.value=dest;document.getElementById('searchBtn')?.click();setTimeout(()=>{let cards=[...document.querySelectorAll('#trailList .trail')].filter(x=>x.style.display!=='none'),best=cards.slice(0,3).map(x=>x.querySelector('.trailName')?.textContent).filter(Boolean);status.textContent=best.length?`Top matches: ${best.join(' • ')}`:`Searching live trail data around ${dest}…`},3500)}
 function save(){let dest=document.getElementById('tripDestination').value.trim();if(!dest)return;let trip={id:Date.now(),destination:dest,date:document.getElementById('tripDate').value,activity:document.getElementById('tripActivity').value,radius:document.getElementById('tripRadius').value,created:new Date().toISOString()};let all=get();all.unshift(trip);put(all.slice(0,20));renderSaved();document.getElementById('tripStatus').textContent=`Trip to ${dest} saved.`}
 function renderSaved(){let el=document.getElementById('tripSaved');if(!el)return;let all=get();el.innerHTML=all.length?'<div class="eyebrow">SAVED TRIPS</div>'+all.map(t=>`<div class="tripItem"><strong>${t.destination}</strong><small>${label(t.activity)} • ${t.date||'Date not set'} • ${t.radius==='all'?'Search farther':t.radius+' min radius'}</small><button class="btn" data-load="${t.id}">Load Trip</button> <button class="btn" data-del="${t.id}">Delete</button></div>`).join(''):'';el.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>load(+b.dataset.load));el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>del(+b.dataset.del))}
 function load(id){let t=get().find(x=>x.id===id);if(!t)return;document.getElementById('tripDestination').value=t.destination;document.getElementById('tripDate').value=t.date;document.getElementById('tripActivity').value=t.activity;document.getElementById('tripRadius').value=t.radius;find()}
 function del(id){put(get().filter(x=>x.id!==id));renderSaved()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();