(()=>{
 const $=id=>document.getElementById(id),checked=id=>!!$(id)?.checked;
 const timeout=(p,ms=10000)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error('timeout')),ms))]);
 const fmt=t=>{let h=+t.slice(11,13);return `${h%12||12} ${h<12?'AM':'PM'}`},end=t=>{let h=(+t.slice(11,13)+1)%24;return `${h%12||12} ${h<12?'AM':'PM'}`};
 function heatIndex(t,rh){if(t<80||rh<40)return Math.round(t);return Math.round(-42.379+2.04901523*t+10.14333127*rh-.22475541*t*rh-.00683783*t*t-.05481717*rh*rh+.00122874*t*t*rh+.00085282*t*rh*rh-.00000199*t*t*rh*rh)}
 function score(t,rain,rh,aqi,oz=0){let f=heatIndex(t,rh),s=10;if(f>=110)s-=8;else if(f>=105)s-=7;else if(f>=100)s-=6;else if(f>=95)s-=4.5;else if(f>=90)s-=3;else if(f>=85)s-=1.5;if(rh>=85)s-=1.5;else if(rh>=75)s-=.8;else if(rh>=65)s-=.3;if(rain>=70)s-=3;else if(rain>=40)s-=1.5;else if(rain>=20)s-=.5;if(aqi!=null){if(aqi>150)s-=3;else if(aqi>100)s-=2;else if(aqi>50)s-=.75}if(checked('respiratory')){if(aqi!=null){if(aqi>100)s-=2;else if(aqi>50)s-=1}if(oz>120)s-=1.5;if(f>=95)s-=1.5;else if(f>=90)s-=.75;if(rh>=80)s-=.75}if(checked('heatSensitive')){if(f>=100)s-=3;else if(f>=95)s-=2;else if(f>=90)s-=1}if(checked('cardio')){if(f>=100)s-=2;else if(f>=95)s-=1.25;else if(f>=90)s-=.5}return Math.max(1,Math.min(10,+s.toFixed(1)))}
 function alertBox(){let b=$('smartRideAlerts');if(b)return b;b=document.createElement('section');b.id='smartRideAlerts';b.style.cssText='margin:12px 0;padding:14px 16px;border-radius:16px;border:1px solid #52686d;color:#fff';document.querySelector('.weatherCard')?.insertAdjacentElement('afterend',b);return b}
 function alerts(f,r,aq,w,storm){let a=[];if(f>=110)a.push(`🚨 EXTREME HEAT • Feels like ${f}°F`);else if(f>=100)a.push(`⚠️ DANGEROUS HEAT • Feels like ${f}°F`);else if(f>=95)a.push(`⚠️ HIGH HEAT • Feels like ${f}°F`);if(storm)a.push('⛈️ THUNDERSTORM RISK • Check radar before riding');if(w>=30)a.push(`💨 HIGH WIND • Gusts near ${Math.round(w)} mph`);if(aq!=null&&aq>100)a.push(`🫁 AIR QUALITY CAUTION • AQI may reach ${Math.round(aq)}`);if(r>=70)a.push(`🌧️ HIGH RAIN CHANCE • ${Math.round(r)}%`);let b=alertBox();b.style.background=a.length?(f>=105?'#651f1f':'#573d18'):'#102a23';b.innerHTML=a.length?'<strong>SMART RIDE WARNINGS</strong><div style="margin-top:7px">'+a.join('<br>')+'</div>':'<strong>✅ No major ride warnings</strong>'}
 async function json(u){let r=await timeout(fetch(u,{cache:'no-store'}));if(!r.ok)throw Error('http');return r.json()}
 async function load(lat,lon){try{$('weatherTitle').textContent='Loading live weather…';let day=$('daySelect')?.value||new Date().toISOString().slice(0,10),[wr,ar]=await Promise.allSettled([json(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_gusts_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto&past_days=2&forecast_days=8`),json(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&hourly=us_aqi,pm2_5,ozone&timezone=auto&forecast_days=7`)]);if(wr.status!=='fulfilled')throw wr.reason;let wx=wr.value,aq=ar.status==='fulfilled'?ar.value:null,di=wx.daily.time.indexOf(day);if(di<0)di=0;let high=Math.round(wx.daily.temperature_2m_max[di]),low=Math.round(wx.daily.temperature_2m_min[di]),rain=Math.round(wx.daily.precipitation_probability_max[di]||0);$('weatherTitle').textContent=`${high}°F high • ${low}°F low • ${rain}% rain`;
 let nowDay=new Date().toLocaleDateString('en-CA'),isToday=day===nowDay;$('weatherSummary').textContent=isToday?`Now ${Math.round(wx.current.temperature_2m)}°F • Wind ${Math.round(wx.current.wind_speed_10m||0)} mph • Humidity ${Math.round(wx.current.relative_humidity_2m||0)}%`:'Forecast conditions • Hour-by-hour planner below.';
 let now=Date.now(),r24=0,r48=0;wx.hourly.time.forEach((t,i)=>{let age=(now-new Date(t).getTime())/36e5,p=+(wx.hourly.precipitation[i]||0);if(age>=0&&age<=24)r24+=p;if(age>=0&&age<=48)r48+=p});$('rainHistory').textContent=`🌧 Recent rainfall: ${r24.toFixed(2)} in. past 24 hr • ${r48.toFixed(2)} in. past 48 hr`;
 let rows=[],aqVals=[],pmVals=[],maxF=-99,maxW=0,storm=false;wx.hourly.time.forEach((t,i)=>{if(t.slice(0,10)!==day)return;let h=+t.slice(11,13);if(h<6||h>20)return;let ai=aq?.hourly?.time?.indexOf(t)??-1,av=ai>=0&&Number.isFinite(+aq.hourly.us_aqi?.[ai])?+aq.hourly.us_aqi[i]:null,pm=ai>=0&&Number.isFinite(+aq.hourly.pm2_5?.[i])?+aq.hourly.pm2_5[i]:null,oz=ai>=0?+(aq.hourly.ozone?.[i]||0):0,tv=+wx.hourly.temperature_2m[i],rh=+wx.hourly.relative_humidity_2m[i],rp=+wx.hourly.precipitation_probability[i],gust=+wx.hourly.wind_gusts_10m[i],code=+wx.hourly.weather_code[i],f=heatIndex(tv,rh);if(av!=null)aqVals.push(av);if(pm!=null)pmVals.push(pm);maxF=Math.max(maxF,f);maxW=Math.max(maxW,gust);if(code>=95)storm=true;rows.push({t,temp:tv,rh,rp,aqi:av,oz,s:score(tv,rp,rh,av,oz)})});
 let maxA=aqVals.length?Math.max(...aqVals):null,maxPm=pmVals.length?Math.max(...pmVals):null;$('airQualitySummary').textContent=maxA==null?'🌬 AQI forecast unavailable':`🌬 AQI ${Math.round(maxA)} • PM2.5 ${maxPm?.toFixed(1)??'--'}`;alerts(maxF,rain,maxA,maxW,storm);
 let best=null;for(let i=0;i<=rows.length-3;i++){let g=rows.slice(i,i+3),avg=g.reduce((z,x)=>z+x.s,0)/3;if(!best||avg>best.avg)best={g,avg}};$('bestWindow').innerHTML=best?`⭐ Best 3-hour window: <strong>${fmt(best.g[0].t)}–${end(best.g[2].t)}</strong> • ${best.avg.toFixed(1)}/10`:'Hourly forecast unavailable.';$('hourlyList').innerHTML=rows.map(x=>`<div class="hour ${x.s>=8?'great':x.s>=6?'fair':'poor'}"><strong>${fmt(x.t)}</strong><span>${Math.round(x.temp)}°</span><small>Feels ${heatIndex(x.temp,x.rh)}°</small><small>Rain ${Math.round(x.rp)}%</small><small>AQI ${x.aqi==null?'--':Math.round(x.aqi)}</small><b>${x.s.toFixed(1)}</b></div>`).join('');$('overallScore').textContent=best?best.avg.toFixed(1):score(high,rain,50,maxA).toFixed(1);window.__trailrideWeatherOK=true}catch(e){$('weatherTitle').textContent='Live weather unavailable';$('weatherSummary').textContent='Tap Refresh to retry.';window.__trailrideWeatherOK=false}}
 function coords(){try{return typeof loc!=='undefined'&&loc?{lat:loc.lat,lon:loc.lon}:{lat:32.46098,lon:-84.98771}}catch{return{lat:32.46098,lon:-84.98771}}}function reload(){let c=coords();load(c.lat,c.lon)}setTimeout(reload,500);$('refreshBtn')?.addEventListener('click',reload);$('daySelect')?.addEventListener('change',reload);$('locateBtn')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude),reload));document.querySelectorAll('.healthOpt').forEach(x=>x.addEventListener('change',reload));window.TrailRideWeather={load,reload,score,heatIndex};
})();