(()=>{
 const $=id=>document.getElementById(id),checked=id=>!!$(id)?.checked;
 function heatIndex(t,rh){if(t<80||rh<40)return Math.round(t);return Math.round(-42.379+2.04901523*t+10.14333127*rh-.22475541*t*rh-.00683783*t*t-.05481717*rh*rh+.00122874*t*t*rh+.00085282*t*rh*rh-.00000199*t*t*rh*rh)}
 function score(t,rain,rh,aqi){let hi=heatIndex(t,rh),s=10;if(hi>=110)s-=8;else if(hi>=105)s-=7;else if(hi>=100)s-=6;else if(hi>=95)s-=4.5;else if(hi>=90)s-=3;else if(hi>=85)s-=1.5;if(rh>=85)s-=1.5;else if(rh>=75)s-=.8;else if(rh>=65)s-=.3;if(rain>=70)s-=3;else if(rain>=40)s-=1.5;else if(rain>=20)s-=.5;if(aqi!=null){if(aqi>150)s-=3;else if(aqi>100)s-=2;else if(aqi>50)s-=.75}if(checked('respiratory')){if(aqi!=null){if(aqi>100)s-=2;else if(aqi>50)s-=1}if(hi>=95)s-=1.5;else if(hi>=90)s-=.75;if(rh>=80)s-=.75}if(checked('heatSensitive')){if(hi>=100)s-=3;else if(hi>=95)s-=2;else if(hi>=90)s-=1}if(checked('cardio')){if(hi>=100)s-=2;else if(hi>=95)s-=1.25;else if(hi>=90)s-=.5}return Math.max(1,Math.min(10,+s.toFixed(1)))}
 async function json(u){let c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{let r=await fetch(u,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error();return await r.json()}finally{clearTimeout(tm)}}
 function coords(){try{return typeof loc!=='undefined'&&loc?{lat:loc.lat,lon:loc.lon}:{lat:32.46098,lon:-84.98771}}catch{return{lat:32.46098,lon:-84.98771}}}
 async function load(lat,lon){let grid=$('weekGrid'),bestEl=$('weekBest');if(!grid)return;grid.innerHTML='<div class="weekDay">Loading 7-day forecast…</div>';try{let [w,a]=await Promise.all([json(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&hourly=temperature_2m,relative_humidity_2m,precipitation_probability&temperature_unit=fahrenheit&timezone=auto&forecast_days=7`),json(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&hourly=us_aqi&timezone=auto&forecast_days=7`).catch(()=>null)]);
 let days=w.daily.time.map((d,i)=>{let hours=[];w.hourly.time.forEach((t,j)=>{let h=+t.slice(11,13);if(t.slice(0,10)!==d||h<6||h>20)return;let ai=a?.hourly?.time?.indexOf(t)??-1,aqi=ai>=0&&Number.isFinite(+a.hourly.us_aqi?.[ai])?+a.hourly.us_aqi[ai]:null,temp=+w.hourly.temperature_2m[j],rh=+w.hourly.relative_humidity_2m[j],rain=+w.hourly.precipitation_probability[j],hi=heatIndex(temp,rh);hours.push({temp,rh,rain,aqi,hi,s:score(temp,rain,rh,aqi)})});let high=Math.round(w.daily.temperature_2m_max[i]),low=Math.round(w.daily.temperature_2m_min[i]),rain=Math.round(w.daily.precipitation_probability_max[i]||0),maxHi=hours.length?Math.max(...hours.map(x=>x.hi)):high,aqs=hours.map(x=>x.aqi).filter(x=>x!=null),aqi=aqs.length?Math.max(...aqs):null,best3=null;for(let j=0;j<=hours.length-3;j++){let avg=hours.slice(j,j+3).reduce((z,x)=>z+x.s,0)/3;if(best3==null||avg>best3)best3=avg}let s=best3==null?score(high,rain,50,aqi):+best3.toFixed(1),alert='';if(maxHi>=110)alert='⚠️ EXTREME HEAT';else if(maxHi>=100)alert='⚠️ DANGEROUS HEAT';else if(maxHi>=95)alert='⚠️ HIGH HEAT';else if(aqi!=null&&aqi>100)alert='⚠️ AIR QUALITY';else if(rain>=60)alert='🌧️ HIGH RAIN CHANCE';return{d,high,low,rain,aqi,hi:maxHi,s,alert}});
 let best=days.reduce((x,y)=>!x||y.s>x.s?y:x,null),bd=new Date(best.d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long'});bestEl.innerHTML=`🏆 <strong>Best day: ${bd} — ${best.s.toFixed(1)}/10</strong><span>${best.high}°F high • ${best.rain}% rain • AQI ${best.aqi==null?'--':Math.round(best.aqi)}</span>`;grid.innerHTML=days.map(x=>{let name=new Date(x.d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'});return `<div class="weekDay ${x===best?'best ':''}${x.s>=8?'great':x.s>=6?'fair':'poor'}"><strong>${name}</strong><span>${x.high}° / ${x.low}°</span><small>Peak feels-like ${x.hi}°</small><small>Rain ${x.rain}%</small><small>AQI ${x.aqi==null?'--':Math.round(x.aqi)}</small><b>${x.s.toFixed(1)}/10</b>${x.alert?`<div class="weekAlert ${x.hi>=105?'danger':'caution'}">${x.alert}</div>`:''}</div>`}).join('')}catch(e){grid.innerHTML='<div class="weekDay">7-day forecast unavailable. Tap Refresh to retry.</div>';bestEl.textContent='Unable to calculate the best ride day.'}}
 function reload(){let c=coords();load(c.lat,c.lon)}setTimeout(reload,700);$('refreshBtn')?.addEventListener('click',reload);$('locateBtn')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude),reload));document.querySelectorAll('.healthOpt').forEach(x=>x.addEventListener('change',reload));window.TrailRideWeek={reload,load,heatIndex};
})();